sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'
  - '5'
  - '4'

env:
  global:
    - secure: "uF85Lr2WQ9LXRMX+m/tYXxSpmLzcQhhHvGlY0aQYeccQD4WaQ9VBrzoEOKlp9MftQL8xSlxhYCbFsFnV01+VZDk8W/EagghnbnBa4ZevSOU/4JAfEZRF80QSPhQHxnRAbTsAB/G6sgWJUHVBL53pTuMg5f0bu9i+45Dha9S0of8aH2QwPj76uPXBRdu6wSu0pYqiw4oSo7BBofcv0cEoZ6pLddJcuuM0o3Tn4/5FnqDwHhtwGr24l7gltjWQjCW+cR0Uh2QSiccZsnZY0Vn4AeK0Y5M/NhzzVy+Gh/v2ALCDTfJ4XqylwWu9aAIrIdVe19GPLkEbt3FySJcnBQKxqH5bLdJhz5BUalZ9gDoEtFPOZcfUSbv9nUSjelDxwH5u3wFWhGMwhDvD14cSgsZkk1xoLc934fwxNufKoxBpj2LQ4I7aTtKaeioIwLvtQxva/0bvKKpvP4gEMZb/ghfTiUXUHW2KqfS7t+kRhKwfJqt2ffBIsD4GDyO5lbeapIng7OVTCL7aVVA9f4PNK7rC1F4inMK3pWqvYsH77wF5GGeTX52CYAU2aBmzD/SNnriW/5ex1THcsCbWi6EClYVDCP5puJiHvDovFGhLFfsBUJ2aUYTqpJz1pLY63mGsoz0Uab1mT0QQytnNdXjpXqUZsEj71hr3NQIUeDJ6tBe7A7o=" # GITHUB_TOKEN

before_install:
  - npm install -g npm
  - npm --version

install:
  - npm install

after_success:
  - mkdir -p releases
  - PACKAGE_NAME=`scripts/package-name.sh package.json`
  - PACKAGE_VERSION=`scripts/package-version.sh package.json`
  - RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
  - COMMIT_LOG=`git log -1 --format='%ci %H %s'`
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      pushd releases;
      ln -sf ../src ${RELEASE};
      zip -r ${RELEASE}.zip ${RELEASE};
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cncjs \
          --repo=cncjs-pendant-tinyweb \
          --tag="${TRAVIS_BRANCH}" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}.zip"
      fi
    fi

before_deploy:
  - echo "Deploying to GitHub releases"
  - ls -al releases

deploy:
  provider: releases
  api_key:
    secure: "NOI9C8hxO49yPPe/ffQVbfnZphZSKeWAO96+3lOovM46aT3K8CGOESSwVuASD+MtLBlYg74LkbhQeV+6Txwv8KtxCYvWAVh1GHbuFfTNw7SvqmLUXD9NHa6B0k5R0st3HjZbVEQ7sGMxbcYRLhC/JNs9uPKGAyGhb/6uj1jgD+hoMme0ijhTHYqaR9PXvkigg3VOmpCpYYj1SvviCfGyCsGtHonyI80ikeQv+LvK9zcDN+fgX4EE38lNnzrCTWTUPUw9VVUvfIKmVzdagvBDrgxdv5RTQkYM5bWRS0CNgLXOBw/foMZCkELBAF50MbDN9mkgnSb8JHm+ayZvD9De+qd/TEymAbJzB4lgFfPkJSDOYA/w2JYnpxbqw+cH+YhJw+OPveGlyE1cd+MCdIxmrGIfbSrM5e1x7S4V2UeWe/7/hjhVVWkmJnxzu8L+IFSCrEUXaHDRrMiyrmKd8c7gpmZrXeO9vo3ExSp+56TfOApG6VQ/xBIJssFet8KCtffusQUAiZp2tKWh6aB4Mv5V5uyOnziLvm8frU3urr4mHhs1cxl4YW3l2BcNwg75npxfWyzxXYaHIzpokQdDCLXIcYxla+E/R1o5uHhOBx7qMW8rJIDa7wIF7mCqHI815eQdIigeosjbP3KRN+SRWbqeRa/fw7Bsnxc1bruea/N+hKk="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: true  # Deploy app only when a tag is applied to the commit
    node: '6'
