sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'
  - '5'
  - '4'

before_install:
  - npm install -g npm
  - npm --version

install:
  - npm install

after_success:
  - mkdir -p releases
  - PACKAGE_NAME=`scripts/package-name.sh package.json`
  - PACKAGE_VERSION=`scripts/package-version.sh package.json`
  - RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
  - COMMIT_LOG=`git log -1 --format='%ci %H %s'`
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      pushd src;
      zip -r "../releases/${RELEASE}.zip" *;
      popd;
      ls -al releases/*;
      if [[ -z "$TRAVIS_TAG" ]]; then
        npm run github-release -- \
          --owner=cncjs \
          --repo=cncjs-pendant-tinyweb \
          --tag="${TRAVIS_BRANCH}" \
          --name="${TRAVIS_BRANCH}" \
          --body="${COMMIT_LOG}" \
          "releases/${RELEASE}.zip"
      fi
    fi

before_deploy:
  - echo "Deploying to GitHub releases"
  - ls -al releases

deploy:
  provider: releases
  api_key:
    secure: "NOI9C8hxO49yPPe/ffQVbfnZphZSKeWAO96+3lOovM46aT3K8CGOESSwVuASD+MtLBlYg74LkbhQeV+6Txwv8KtxCYvWAVh1GHbuFfTNw7SvqmLUXD9NHa6B0k5R0st3HjZbVEQ7sGMxbcYRLhC/JNs9uPKGAyGhb/6uj1jgD+hoMme0ijhTHYqaR9PXvkigg3VOmpCpYYj1SvviCfGyCsGtHonyI80ikeQv+LvK9zcDN+fgX4EE38lNnzrCTWTUPUw9VVUvfIKmVzdagvBDrgxdv5RTQkYM5bWRS0CNgLXOBw/foMZCkELBAF50MbDN9mkgnSb8JHm+ayZvD9De+qd/TEymAbJzB4lgFfPkJSDOYA/w2JYnpxbqw+cH+YhJw+OPveGlyE1cd+MCdIxmrGIfbSrM5e1x7S4V2UeWe/7/hjhVVWkmJnxzu8L+IFSCrEUXaHDRrMiyrmKd8c7gpmZrXeO9vo3ExSp+56TfOApG6VQ/xBIJssFet8KCtffusQUAiZp2tKWh6aB4Mv5V5uyOnziLvm8frU3urr4mHhs1cxl4YW3l2BcNwg75npxfWyzxXYaHIzpokQdDCLXIcYxla+E/R1o5uHhOBx7qMW8rJIDa7wIF7mCqHI815eQdIigeosjbP3KRN+SRWbqeRa/fw7Bsnxc1bruea/N+hKk="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: true  # Deploy app only when a tag is applied to the commit
    node: '6'
